[shell]

program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session -A -s main"]


[window]

padding = { x = 4, y = 4 }
decorations = "Buttonless"
option_as_alt = "OnlyLeft"


[font]

normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Retina" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "SemiBold Italic" }
size = 14.5


[cursor]

style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Beam", blinking = "Always" }
blink_interval = 500
blink_timeout = 0


[keyboard]

bindings = [
  { key = "Back", mods = "Control", chars = "\u0017" }, # <C-BS>
]
