#!/usr/bin/env python3

import atexit
import os
import readline

cache_dir = os.environ.get("XDG_CACHE_HOME") or os.path.expanduser("~/.cache")
history = os.path.join(cache_dir, "python_history")
try:
    readline.read_history_file(history)
except OSError:
    pass


def write_history():
    try:
        os.makedirs(cache_dir, exist_ok=True)
        readline.write_history_file(history)
    except OSError:
        pass


atexit.register(write_history)
